### ISSUE TITLE
Make README more helpful for those who don't know about flame graphs

### ISSUE THREAD

**Issue by jonhoo** [ferrous-systems/cargo-flamegraph#14]
Someone [pointed out](https://www.reddit.com/r/rust/comments/b08oex/cargoflamegraph_generate_flame_graphs_directly/eid9x76/) that it'd be good to at least include an example flame graph in the README. I suspect adding a tiny bit of information about what flame graphs are (like how to read them) + link to http://www.brendangregg.com/flamegraphs.html would also be a good addition.

**Comment by spacejam** [comment]
Just added a small example image after hand-tweaking the svg to make it smaller.

I think this would be a good place for a mini-guide on systems perf theory, maybe a little queue theory :D

**Comment by spacejam** [comment]
added some misc info about profiling and perf theory https://github.com/ferrous-systems/cargo-flamegraph#systems-performance-work-guided-by-flamegraphs

**Comment by jonhoo** [comment]
Looks really good!

A few minor notes:
 - Under "Flamegraphs Are the Beginning, Not the End", I wonder if we should also link to Brendan's posts on Off-CPU profiling, eBPF, etc. which go beyond just traditional flame graphs.
 - The link to 'Ferrous Systems' at the end also seems to be broken?
 - Not a must, but I'd appreciate a link back to inferno :)

**Comment by jonhoo** [comment]
@spacejam quick bump re ^

**Comment by spacejam** [comment]
@jonhoo added! [sorry for the delay, was giving a rust training all week abroad]
