### ISSUE TITLE
split into flamegraph for arbitrary executables and cargo-flamegraph for Rust projects

### ISSUE THREAD

**Issue by spacejam** [ferrous-systems/cargo-flamegraph#7]
This binary is already helpful for reducing dependencies and friction to generate flamegraphs, but we can go farther by generating a simple `flamegraph` binary that skips the cargo-specific stuff and can be used for arbitrary workloads.

**Comment by jonhoo** [comment]
Seems like a great idea. We'd probably also want to support `--` for passing arguments to custom binaries instead of just placing them inside a string argument to `--exec`.

**Comment by spacejam** [comment]
done
